# Generated by Django 2.0.3 on 2018-10-25 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_description', models.TextField()),
                ('sample_input', models.CharField(max_length=200)),
                ('sample_output', models.CharField(max_length=200)),
                ('sample_exp', models.TextField()),
                ('interactor', models.CharField(max_length=200)),
                ('prob_title', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField(default=1)),
                ('memory_limit', models.IntegerField(default=256)),
                ('type', models.IntegerField(choices=[('0', 'Nothing'), ('1', 'UserInput'), ('2', 'InteractorInput'), ('3', 'Both')], default='0')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=5, max_digits=7)),
                ('verdict', models.IntegerField(choices=[('0', 'Ac'), ('1', 'Wa'), ('2', 'Tle'), ('3', 'Ceu'), ('4', 'Cei'), ('5', 'Se')])),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_judge.Problems')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_judge.Problems')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfile_user', models.CharField(default=None, max_length=100)),
                ('testfile_interactor', models.CharField(default=None, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_judge.Problems')),
            ],
        ),
        migrations.AddField(
            model_name='problemsubmission',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_judge.Submissions'),
        ),
        migrations.AddField(
            model_name='problemsubmission',
            name='testid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_judge.TestCase'),
        ),
    ]
