# Generated by Django 2.0.3 on 2018-10-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='type',
            field=models.IntegerField(choices=[(0, 'Nothing'), (1, 'UserInput'), (2, 'InteractorInput'), (3, 'Both')], default=0),
        ),
        migrations.AlterField(
            model_name='problemsubmission',
            name='verdict',
            field=models.IntegerField(choices=[(0, 'Ac'), (1, 'Wa'), (2, 'Tle'), (3, 'Ceu'), (4, 'Cei'), (5, 'Se')]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testfile_interactor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testfile_user',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
