# Generated by Django 2.0.3 on 2018-10-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_judge', '0002_auto_20181026_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='type',
            new_name='input_type',
        ),
    ]
